### ISSUE TITLE
Make it possible to select schemas

### ISSUE THREAD

**Issue by vad-bal** [mmvergara/supadart#88]
Hi

I think it would be a really useful feature to be able to select different schemas to generate classes for.

There could be an option in the config like `schemas:` with the default value of `public` to keep it compatible.
Also, the mappings would need to updated to specify schema of the mapped table.

Here is an example how a valid config could look like:
```
schemas:
  - public
  - myschema
mappings:
  public.items: Item
  public.mytable: MyClass
  myschema.mytable: MyOtherClass
```

Of course when selecting a single schema, the mapping keys can be the same as before.
